name: OGC API Validator

on:
  pull_request:
  merge_group:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ogc-api-processes-validator:
    name: Validate OGC API - Processes compliance
    runs-on: ubuntu-latest

    steps:
      - name: Dependencies
        run: |
          sudo apt-get update
            sudo apt-get install -y \
              build-essential \
              pkg-config \
              libclang-dev \
              libgdal-dev \
              python3-dotenv

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: docker compose up db -d

      - name: Start service
        run: cargo run -p demo-service &

      - name: Validate service
        uses: geo-engine/ogc-validator@v1
        with:
          service-url: http://localhost:8484/
          ogc-api-processes: true
          ogc-api-processes-version: 1.3-teamengine-6.0.0-RC2
          echoprocessid: echo
          ogc-api-processes-ignore: |-
            testJobCreationOp
            testJobCreationInputValidation
            testJobCreationRequest
            testJobCreationInputRef
            testJobList
